### PR TITLE
CB-1002 Make CLI work again with UMS authentication

### PR DESCRIPTION
**Pull request by bbihari**

### CODE REVIEW

**Comment by akanto** [comment]
The code looks good, I have tested it but it seems something is not correct.

```
~/.dp $ dp env list
ERROR: status code: 401, message: {"error":"JWT token required"}

~/.dp $ cat config
default:
  server: https://***.cloudera.com
  workspace: a***@***dera.com
  apikeyid: 12334343-*******644c9
  privatekey: RQiE********hzUWo=
``

**Comment by giladwolff** [comment]
I commented on Slack as well, but where is the signature generated? I may be missing something as I am new to go and to the review tool?

**Comment by sodre90** [comment]
I am not sure if dps-gateway is the latest version on manowar env, it can be a problem.

**Comment by giladwolff** [comment]
The dps-gateway is not updated yet. I am waiting for another ship it before merging it in (it's a long weekend in India).

**Pull request merged**
