### PR TITLE
BUG-96896: Cloudbreak CLI Docker Image is non-functional

### PR DESCRIPTION
**Pull request by tibkiss**

### CODE REVIEW

**Comment by mhmxs** [comment]
We are using BUG in commit message instead of CLOUD. Could you please change commit message, would be nice to see commit on issue tracker.

**Comment by tibkiss** [comment]
Sure, changed both the commit msg & pr title.

**Comment by mhmxs** [comment]
Otherwise, nice catch mate ;)

**Comment by tibkiss** [comment]
that's already taken care of with the -t parameter:
Another great `apk add` feature for cleanup is the concept of virtual packages using the `--virtual` or `-t` switch. Packages added under this virtual name can then be removed as one group. An example use of this would be removing a group of build dependencies all at once:

build-deps will be a logical group for musl-dev git and go and got deleted at the end.

**Comment by mhmxs** [comment]
Good to know. thanks.

**Pull request merged**
